In [1]:
# To use the URL to python
import requests
import pandas as pd
import time  # For handling delays

In [2]:
# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [3]:
api_key = 'api_key_here'

In [4]:
# Sending a get request to TMDB API to fetch the list of popular movies (page 1) in English
requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language=en-US&page=1')

In [5]:
# To see the data - use .json() after the above 
requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language=en-US&page=1').json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg',
   'genre_ids': [878, 28, 12],
   'id': 912649,
   'original_language': 'en',
   'original_title': 'Venom: The Last Dance',
   'overview': "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
   'popularity': 3047.508,
   'poster_path': '/aosm8NMQ3UyoBVpSxyimorCQykC.jpg',
   'release_date': '2024-10-22',
   'title': 'Venom: The Last Dance',
   'video': False,
   'vote_average': 6.489,
   'vote_count': 789},
  {'adult': False,
   'backdrop_path': '/18TSJF1WLA4CkymvVUcKDBwUJ9F.jpg',
   'genre_ids': [27, 53, 9648],
   'id': 1034541,
   'original_language': 'en',
   'original_title': 'Terrifier 3',
   'overview': "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
   'popularity': 1929.351,
   'poster_path': '/l1175hgL5DoXnqeZQCcU3eZIdhX.jpg',
   'release_date': '2024-10-09',
   'title': 'Terrifier 3',
   'video': False,
   'vote_average': 6.909,
   'vote_count': 1031},
  {'adult': False,
   'backdrop_path': '/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg',
   'genre_ids': [16, 878, 10751],
   'id': 1184918,
   'original_language': 'en',
   'original_title': 'The Wild Robot',
   'overview': "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
   'popularity': 1808.363,
   'poster_path': '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
   'release_date': '2024-09-12',
   'title': 'The Wild Robot',
   'video': False,
   'vote_average': 8.471,
   'vote_count': 2938},
  {'adult': False,
   'backdrop_path': '/2fxnTXr8NwyTFkunkimJkGkhqfy.jpg',
   'genre_ids': [18, 28, 27],
   'id': 1118031,
   'original_language': 'es',
   'original_title': 'Apocalipsis Z: el principio del fin',
   'overview': 'When a kind of rabies that transforms people into aggressive creatures spreads across the planet, Manel isolates himself at home with his cat, relying on his wits to survive; but soon they must go out in search of food, by land and by sea, dodging many dangers.',
   'popularity': 1638.618,
   'poster_path': '/wIGJnIFQlESkC2rLpfA8EDHqk4g.jpg',
   'release_date': '2024-10-04',
   'title': 'Apocalypse Z: The Beginning of the End',
   'video': False,
   'vote_average': 6.784,
   'vote_count': 498},
  {'adult': False,
   'backdrop_path': '/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg',
   'genre_ids': [28, 12, 18],
   'id': 558449,
   'original_language': 'en',
   'original_title': 'Gladiator II',
   'overview': 'Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.',
   'popularity': 1742.5,
   'poster_path': '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
   'release_date': '2024-11-13',
   'title': 'Gladiator II',
   'video': False,
   'vote_average': 6.791,
   'vote_count': 450},
  {'adult': False,
   'backdrop_path': '/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
   'genre_ids': [28, 35, 878],
   'id': 533535,
   'original_language': 'en',
   'original_title': 'Deadpool & Wolverine',
   'overview': 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
   'popularity': 1327.058,
   'poster_path': '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
   'release_date': '2024-07-24',
   'title': 'Deadpool & Wolverine',
   'video': False,
   'vote_average': 7.7,
   'vote_count': 5488},
  {'adult': False,
   'backdrop_path': '/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg',
   'genre_ids': [18, 27, 878],
   'id': 933260,
   'original_language': 'en',
   'original_title': 'The Substance',
   'overview': 'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
   'popularity': 1205.748,
   'poster_path': '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
   'release_date': '2024-09-07',
   'title': 'The Substance',
   'video': False,
   'vote_average': 7.274,
   'vote_count': 2082},
  {'adult': False,
   'backdrop_path': '/1FBHAQnq7Bs3djBmaNkfdVbnCUE.jpg',
   'genre_ids': [28, 53],
   'id': 1124641,
   'original_language': 'en',
   'original_title': 'Classified',
   'overview': 'Operating alone in the field for more than 20 years, a CIA hitman uses the "Help Wanted" section of the newspapers to get his orders from the Agency. His long-lost daughter, now a UK MI6 analyst, tracks him down to deliver shocking news: his CIA boss has been dead for years and the division long since shut down. Together, they set out to discover whose orders he\'s been executing.',
   'popularity': 1158.653,
   'poster_path': '/3k8jv1kSAAc0rCfFGtWDDQL4dfK.jpg',
   'release_date': '2024-09-19',
   'title': 'Classified',
   'video': False,
   'vote_average': 5.545,
   'vote_count': 56},
  {'adult': False,
   'backdrop_path': '/2h9yTYWTb909J28bzNTIE7dyNqP.jpg',
   'genre_ids': [16, 878, 12, 10751],
   'id': 698687,
   'original_language': 'en',
   'original_title': 'Transformers One',
   'overview': 'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
   'popularity': 1113.84,
   'poster_path': '/qbkAqmmEIZfrCO8ZQAuIuVMlWoV.jpg',
   'release_date': '2024-09-11',
   'title': 'Transformers One',
   'video': False,
   'vote_average': 8.1,
   'vote_count': 727},
  {'adult': False,
   'backdrop_path': '/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg',
   'genre_ids': [28, 35, 14],
   'id': 845781,
   'original_language': 'en',
   'original_title': 'Red One',
   'overview': "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
   'popularity': 920.72,
   'poster_path': '/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg',
   'release_date': '2024-10-31',
   'title': 'Red One',
   'video': False,
   'vote_average': 6.588,
   'vote_count': 136},
  {'adult': False,
   'backdrop_path': '/kwXycPsLA6SV3KUOagn343TtMOf.jpg',
   'genre_ids': [28, 878, 53],
   'id': 791042,
   'original_language': 'en',
   'original_title': 'Levels',
   'overview': "After witnessing his girlfriend's murder, a man risks everything - including reality itself - to discover the truth.",
   'popularity': 1381.644,
   'poster_path': '/y1xm0jMIlx9Oo2a3jWNyLGm43sJ.jpg',
   'release_date': '2024-11-01',
   'title': 'Levels',
   'video': False,
   'vote_average': 5.441,
   'vote_count': 17},
  {'adult': False,
   'backdrop_path': '/6vn6K9oX82i6E86ZiHVxqVEMQqP.jpg',
   'genre_ids': [878, 27],
   'id': 945961,
   'original_language': 'en',
   'original_title': 'Alien: Romulus',
   'overview': 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
   'popularity': 946.215,
   'poster_path': '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
   'release_date': '2024-08-13',
   'title': 'Alien: Romulus',
   'video': False,
   'vote_average': 7.3,
   'vote_count': 2329},
  {'adult': False,
   'backdrop_path': '/9msuazXGWAyl7vhxVFU7e7Bb5Ik.jpg',
   'genre_ids': [18, 10749],
   'id': 179387,
   'original_language': 'tl',
   'original_title': 'Heavenly Touch',
   'overview': 'Jonard is having trouble making ends meet. His mother is suffering from depression, and he and his sister are forced to quit school in order to take care of her. One day, Jonard meets up his friend Rodel, and Rodel introduces him to the world of massage parlors. Rodel teaches him massage, and brings him to Heavenly Touch, a syndicate-run massage parlor that mostly caters to homosexuals.',
   'popularity': 887.512,
   'poster_path': '/ory8WuAqznTE7lfopTSymHpop2t.jpg',
   'release_date': '2009-05-12',
   'title': 'Heavenly Touch',
   'video': False,
   'vote_average': 6.477,
   'vote_count': 22},
  {'adult': False,
   'backdrop_path': '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
   'genre_ids': [16, 10751, 35, 28],
   'id': 519182,
   'original_language': 'en',
   'original_title': 'Despicable Me 4',
   'overview': 'Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
   'popularity': 825.498,
   'poster_path': '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
   'release_date': '2024-06-20',
   'title': 'Despicable Me 4',
   'video': False,
   'vote_average': 7.086,
   'vote_count': 2179},
  {'adult': False,
   'backdrop_path': '/3rxoUVI74z7rTWYSAC2q3Uax2nC.jpg',
   'genre_ids': [27, 9648],
   'id': 1100782,
   'original_language': 'en',
   'original_title': 'Smile 2',
   'overview': 'About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.',
   'popularity': 850.72,
   'poster_path': '/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg',
   'release_date': '2024-10-16',
   'title': 'Smile 2',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 448},
  {'adult': False,
   'backdrop_path': '/9s9o9RT9Yj6nDuRJjnJm78WFoFl.jpg',
   'genre_ids': [28, 27, 53, 878],
   'id': 1051896,
   'original_language': 'en',
   'original_title': 'Arcadian',
   'overview': 'In the near future, on a decimated Earth, Paul and his twin sons face terror at night when ferocious creatures awaken. When Paul is nearly killed, the boys come up with a plan for survival, using everything their father taught them to keep him alive.',
   'popularity': 866.949,
   'poster_path': '/spWV1eRzlDxvai8LbxwAWR0Vst4.jpg',
   'release_date': '2024-04-12',
   'title': 'Arcadian',
   'video': False,
   'vote_average': 6.059,
   'vote_count': 441},
  {'adult': False,
   'backdrop_path': '/n9Do4rv1Hl3QvQLMmT5w6pBadqq.jpg',
   'genre_ids': [28, 10749, 18],
   'id': 1142518,
   'original_language': 'fr',
   'original_title': 'Libre',
   'overview': "Inspired by the true events of one of France's most notorious non-violent robbers, Bruno Sulak, in the 1980s. He led multiple heists, then captured public attention for his many daring escapes from police custody...always to reunite with his beloved lover and accomplice Annie, becoming both France's Public Enemy #1 and an icon of Freedom.",
   'popularity': 624.052,
   'poster_path': '/b2YL2kncIqlcDcqly78AsOPJi6r.jpg',
   'release_date': '2024-11-01',
   'title': 'Freedom',
   'video': False,
   'vote_average': 6.536,
   'vote_count': 56},
  {'adult': False,
   'backdrop_path': '/uVlUu174iiKhsUGqnOSy46eIIMU.jpg',
   'genre_ids': [18, 14, 10749],
   'id': 402431,
   'original_language': 'en',
   'original_title': 'Wicked',
   'overview': 'Elphaba, an ostracized but defiant girl born with green skin, and Galinda, a privileged aristocrat born popular, become extremely unlikely friends in the magical Land of Oz. As the two girls struggle with their opposing personalities, their friendship is tested as both begin to fulfil their destinies as Glinda the Good and The Wicked Witch of the West.',
   'popularity': 927.236,
   'poster_path': '/c5Tqxeo1UpBvnAc3csUm7j3hlQl.jpg',
   'release_date': '2024-11-20',
   'title': 'Wicked',
   'video': False,
   'vote_average': 7.5,
   'vote_count': 30},
  {'adult': False,
   'backdrop_path': '/6VoxDupaW2VXfLtJyeOoGCgXSjD.jpg',
   'genre_ids': [28, 53],
   'id': 1116490,
   'original_language': 'en',
   'original_title': 'Cash Out',
   'overview': 'Criminal mastermind Mason is about to execute the score of a lifetime when his lover and key member of his crew, Decker, takes the team down and reveals she’s an undercover Interpol agent. Heartbroken, Mason escapes and retires from the life of crime until his younger brother Shawn is out of his league taking on a big bank heist all on his own. Mason has no choice left but to come to the rescue, while Interpol brings Decker in hoping to unnerve him. Before the SWAT teams storm the bank, Mason must use every tool in his arsenal to not only escape with the prize, but also the love of his life.',
   'popularity': 712.465,
   'poster_path': '/xBJnIvRdL0nDHgvivr6EgBQizes.jpg',
   'release_date': '2024-04-26',
   'title': 'Cash Out',
   'video': False,
   'vote_average': 6.3,
   'vote_count': 113},
  {'adult': False,
   'backdrop_path': '/2QR0OpYzPFG84EswxENqcPuHmP.jpg',
   'genre_ids': [10752],
   'id': 1041317,
   'original_language': 'en',
   'original_title': 'Battle for the Western Front',
   'overview': 'Inspired by Canuck WWI flying ace Billy Bishop, two young soldiers crash the front lines in August 1918. With the Allies detained, their platoon must desperately hold out alongside legendary Anishinaabe sniper Francis "Peggy" Pegahmagabow.',
   'popularity': 700.758,
   'poster_path': '/ooHEL3XyLYu3hus5cMnpjeH4e7A.jpg',
   'release_date': '2022-10-06',
   'title': 'Battle for the Western Front',
   'video': False,
   'vote_average': 2.875,
   'vote_count': 4}],
 'total_pages': 47235,
 'total_results': 944689}

In [6]:
response = requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language=en-US&page=1').json()

In [7]:
response['total_results']

944689

In [8]:
response['total_pages']

47235

In [9]:
# Extracting relevant movie details from the API response and storing them in a list of dictionaries
movie_data = []
for i in response['results']:
    movie_data.append({
        'title': i['title'],
        'overview': i.get('overview', ''),
        'original_language': i['original_language'],
        'release_date': i.get('release_date', ''),
        'popularity': i['popularity'],
        'vote_count': i['vote_count'],
        'vote_average': i['vote_average']
    })
df = pd.DataFrame(movie_data)

In [10]:
df

,title,overview,original_language,release_date,popularity,vote_count,vote_average
0,Venom: The Last Dance,Eddie and Venom are on the run. Hunted by both...,en,2024-10-22,3047.508,789,6.489
1,Terrifier 3,Five years after surviving Art the Clown's Hal...,en,2024-10-09,1929.351,1031,6.909
2,The Wild Robot,"After a shipwreck, an intelligent robot called...",en,2024-09-12,1808.363,2938,8.471
3,Apocalypse Z: The Beginning of the End,When a kind of rabies that transforms people i...,es,2024-10-04,1638.618,498,6.784
4,Gladiator II,Years after witnessing the death of the revere...,en,2024-11-13,1742.500,450,6.791
5,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,en,2024-07-24,1327.058,5488,7.700
6,The Substance,A fading celebrity decides to use a black mark...,en,2024-09-07,1205.748,2082,7.274
7,Classified,Operating alone in the field for more than 20 ...,en,2024-09-19,1158.653,56,5.545
8,Transformers One,The untold origin story of Optimus Prime and M...,en,2024-09-11,1113.840,727,8.100
9,Red One,After Santa Claus (codename: Red One) is kidna...,en,2024-10-31,920.720,136,6.588
10,Levels,"After witnessing his girlfriend's murder, a ma...",en,2024-11-01,1381.644,17,5.441
11,Alien: Romulus,While scavenging the deep ends of a derelict s...,en,2024-08-13,946.215,2329,7.300
12,Heavenly Touch,Jonard is having trouble making ends meet. His...,tl,2009-05-12,887.512,22,6.477
13,Despicable Me 4,"Gru and Lucy and their girls—Margo, Edith and ...",en,2024-06-20,825.498,2179,7.086
14,Smile 2,"About to embark on a new world tour, global po...",en,2024-10-16,850.720,448,6.900
15,Arcadian,"In the near future, on a decimated Earth, Paul...",en,2024-04-12,866.949,441,6.059
16,Freedom,Inspired by the true events of one of France's...,fr,2024-11-01,624.052,56,6.536
17,Wicked,"Elphaba, an ostracized but defiant girl born w...",en,2024-11-20,927.236,30,7.500
18,Cash Out,Criminal mastermind Mason is about to execute ...,en,2024-04-26,712.465,113,6.300
19,Battle for the Western Front,Inspired by Canuck WWI flying ace Billy Bishop...,en,2022-10-06,700.758,4,2.875

In [12]:
all_movie_data = []

for j in range(1, 501): # Data for pages 1 to 500
    response = requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key={api_key}&language=en-US&page={j}').json()

    movie_data = []
    for i in response['results']:
        movie_data.append({
            'title': i.get('title', 'N/A'),
            'movie_ID': i.get('id', None),
            'overview': i.get('overview', ''),
            'original_language': i.get('original_language', 'N/A'),
            'release_date': i.get('release_date', 'N/A'),
            'popularity': i.get('popularity', 0),
            'vote_count': i.get('vote_count', 0),
            'vote_average': i.get('vote_average', 0)
        })
    
    all_movie_data.extend(movie_data)

In [14]:
# Convert the collected movie data to a DataFrame
df = pd.DataFrame(all_movie_data)

# Save the DataFrame to a CSV file
df.to_csv('Movies.csv', index=False)

print("Data collection complete. Data saved to 'Movies.csv'.")

Data collection complete. Data saved to 'Movies.csv'.

In [15]:
df['overview'] = df['overview'].replace({r'\n': ' ', r'\r': ' '}, regex=True)

# Save the cleaned DataFrame to a new CSV file
df.to_csv('Cleaned_Movies.csv', index=False)

print("Line breaks in 'overview' column replaced. Data saved to 'Cleaned_Movies.csv'.")

Line breaks in 'overview' column replaced. Data saved to 'Cleaned_Movies.csv'.

### Extracting the details of the movie using movie id

In [16]:
movies_df = pd.read_csv('Cleaned_Movies.csv')
movie_ids = movies_df['movie_ID'].dropna().unique()

In [17]:
print(len(movie_ids))

9130

In [ ]:
movie_details = []

# Loop through movie IDs and fetch details
for idx, movie_id in enumerate(movie_ids, 1):
    try:
        # Make the API request
        response = requests.get(
            f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}').json()

        # Append the details for each movie
        movie_details.append({
            'movie_ID': movie_id,
            'budget': response.get('budget', 0),
            'genres': [genre['name'] for genre in response.get('genres', [])],
            'homepage': response.get('homepage', ''),
            'production_companies': [company['name'] for company in response.get('production_companies', [])],
            'production_countries': [country['name'] for country in response.get('production_countries', [])],
            'revenue': response.get('revenue', 0),
            'runtime': response.get('runtime', None)
        })

        # Print progress every 100 movies
        if idx % 100 == 0:
            print(f"Processed {idx}/{len(movie_ids)} movies...")

        # Add a delay to respect API rate limits
        time.sleep(0.4)

    except Exception as e:
        print(f"Error fetching details for movie ID {movie_id}: {e}")

# Convert the movie details into a DataFrame
details_df = pd.DataFrame(movie_details)

# Save the DataFrame to a CSV file
details_df.to_csv('Details.csv', index=False)

print("Movie details collection complete. Data saved to 'Details.csv'.")

All the movies were processed and stored in Details.csv

### Dropping the dupliacted rows in Cleaned_movies.csv

In [33]:
cleaned_movies_df = pd.read_csv('Cleaned_Movies.csv')

# Drop duplicate rows based on the 'movie_ID' column
cleaned_movies_df = cleaned_movies_df.drop_duplicates(subset='movie_ID')

# Save the cleaned data back to CSV
cleaned_movies_df.to_csv('Cleaned_Movies_1.csv', index=False)

# Print the shape to verify the number of rows and columns
print(f"Cleaned data: {cleaned_movies_df.shape[0]} rows, {cleaned_movies_df.shape[1]} columns")

Cleaned data: 9130 rows, 8 columns

### Combining the movies and details Datasets

In [34]:
updated_details_df

,movie_ID,budget,genres,homepage,production_companies,production_countries,revenue,runtime
0,912649,120000000,"['Science Fiction', 'Action', 'Adventure']",https://venom.movie,"['Columbia Pictures', 'Pascal Pictures', 'Matt...",['United States of America'],394000000,109
1,1034541,2000000,"['Horror', 'Thriller', 'Mystery']",https://terrifier3.com/,"['Cineverse', 'Bloody Disgusting', 'Dark Age C...",['United States of America'],78573405,125
2,1184918,78000000,"['Animation', 'Science Fiction', 'Family']",https://www.thewildrobotmovie.com,['DreamWorks Animation'],['United States of America'],308583746,102
3,1118031,0,"['Drama', 'Action', 'Horror']",https://nostromopictures.com/en/movies/coming-...,['Nostromo Pictures'],['Spain'],0,119
4,558449,310000000,"['Action', 'Adventure', 'Drama']",https://www.gladiator.movie,"['Paramount Pictures', 'Red Wagon Entertainmen...",['United States of America'],87000000,148
...,...,...,...,...,...,...,...,...
9125,25633,1758000,"[Crime, Drama, Romance]",,"[Euterpe Productions, Metro-Goldwyn-Mayer]",[United States of America],2380000,99
9126,1048522,3000000,"[Comedy, Drama]",https://www.musicboxfilms.com/film/fremont/,"[Butimar Productions, Extra A Productions, Blu...",[United States of America],600376,92
9127,38745,112000000,"[Family, Comedy, Adventure, Fantasy]",,"[Dune Entertainment, Davis Entertainment, Dune...",[United States of America],237382724,85
9128,373569,42000000,"[Action, Comedy]",,"[Chernin Entertainment, Feigco Entertainment, ...",[United States of America],60800000,90
9129,39057,0,"[Family, Animation, Adventure, Fantasy]",https://www.pokemon.com/us/pokemon-episodes/po...,"[OLM, Pikachu Project, The Pokémon Company, Sh...",[Japan],50673078,94

In [35]:
cleaned_movies_df

,title,movie_ID,overview,original_language,release_date,popularity,vote_count,vote_average
0,Venom: The Last Dance,912649,Eddie and Venom are on the run. Hunted by both...,en,2024-10-22,3047.508,789,6.489
1,Terrifier 3,1034541,Five years after surviving Art the Clown's Hal...,en,2024-10-09,1929.351,1031,6.909
2,The Wild Robot,1184918,"After a shipwreck, an intelligent robot called...",en,2024-09-12,1808.363,2938,8.471
3,Apocalypse Z: The Beginning of the End,1118031,When a kind of rabies that transforms people i...,es,2024-10-04,1638.618,498,6.784
4,Gladiator II,558449,Years after witnessing the death of the revere...,en,2024-11-13,1742.500,450,6.791
...,...,...,...,...,...,...,...,...
9173,Death Hunt,26444,"Yukon Territory, Canada, November 1931. Albert...",en,1981-04-15,20.825,177,6.600
9174,New Female Secretary,918487,"Choi Kyeong-ri, a job seeker, succeeds in find...",ko,2021-12-16,8.924,2,7.000
9175,Get the Gringo,80389,A career criminal nabbed by Mexican authoritie...,en,2012-03-15,20.822,1622,6.600
9176,Trouble,570480,A pampered dog named Trouble must learn to liv...,en,2019-08-08,19.490,220,6.582
9177,Sahara,423453,A young cobra and his scorpion best friend go ...,fr,2017-02-01,20.821,276,5.900

In [36]:
# Merge the two DataFrames on the 'movie_ID' column
combined_df = pd.merge(cleaned_movies_df, updated_details_df, on='movie_ID', how='left')

# Save the combined dataset to a new CSV file
combined_df.to_csv('../data/Combined_Movies_Details.csv', index=False)

# Printing the shape of the combined DataFrame to verify
print(f"Combined data: {combined_df.shape[0]} rows, {combined_df.shape[1]} columns")

Combined data: 9130 rows, 15 columns

## Adding cast and crew Details

In [37]:
details_df = pd.read_csv('../data/Combined_Movies_Details.csv')

movie_ids = details_df['movie_ID'].values

In [ ]:
# List to store the newly fetched movie details (movie_id, director, top_3_actors)
new_movie_details = []

# Loop through each movie ID in your dataset
for movie_id in movie_ids:
    try:
        # Fetch cast and crew data from the TMDB API using the movie ID
        response = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}/credits?api_key={api_key}')
        movie_data = response.json()

        # Extract the director's name from the crew
        director = None
        for member in movie_data.get('crew', []):
            if member['job'] == 'Director':
                director = member['name']
                break
        
        # Extract the top 3 actors' names from the cast (limit to the first 3 actors)
        actors = [actor['name'] for actor in movie_data.get('cast', [])[:3]]

        # Create a dictionary with movie details (ID, Director, Top 3 Actors)
        movie_detail = {
            'movie_ID': movie_id,
            'director': director,
            'top_actors': ', '.join(actors)  # Join top 3 actors' names with commas
        }

        # Add the movie details to the list
        new_movie_details.append(movie_detail)

        # Adding a delay to prevent hitting the API too frequently
        time.sleep(0.4)

    except Exception as e:
        print(f"Error fetching details for movie ID {movie_id}: {e}")

# Convert the new movie details to a DataFrame
new_details_df = pd.DataFrame(new_movie_details)

# Save the DataFrame to a CSV file
new_details_df.to_csv('../data/Movie_Crew_Details.csv', index=False)

In [49]:
# Load the datasets
combined_movies_df = pd.read_csv('../data/Combined_Movies_Details.csv')
crew_df = pd.read_csv('../data/Movie_Crew_Details.csv')

# Merge the two datasets based on 'movie_ID'
final_df = pd.merge(combined_movies_df, crew_df, on='movie_ID', how='left')

# Save the final dataset
final_df.to_csv('../data/complete_movie_dataset.csv', index=False)

print("Datasets have been successfully merged and saved as 'complete_movie_dataset.csv'.")

Datasets have been successfully merged and saved as 'complete_movie_dataset.csv'.

### Adding Keywords

In [ ]:
details_df = pd.read_csv('../data/Combined_Movies_Details.csv')

movie_ids = details_df['movie_ID'].values

# List to store the newly fetched movie details (movie_id, keywords)
new_movie_keywords = []

# Loop through each movie ID in your dataset
for movie_id in movie_ids:
    try:
        # Fetch movie keywords from the TMDB API using the movie ID
        response = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}/keywords?api_key={api_key}&language=en-US')
        movie_data = response.json()

        # Extract the keywords (list of dictionaries)
        keywords = [keyword['name'] for keyword in movie_data.get('keywords', [])]

        # Create a dictionary with movie details (ID, Keywords)
        movie_keyword_detail = {
            'movie_ID': movie_id,
            'keywords': ', '.join(keywords)  # Join keywords with commas
        }

        # Add the movie details to the list
        new_movie_keywords.append(movie_keyword_detail)

        # Adding a delay to prevent hitting the API too frequently
        time.sleep(0.4)

    except Exception as e:
        print(f"Error fetching keywords for movie ID {movie_id}: {e}")

# Convert the new movie keywords to a DataFrame
new_keywords_df = pd.DataFrame(new_movie_keywords)

# Save the DataFrame to a CSV file
new_keywords_df.to_csv('movie_keywords.csv', index=False)

### Adding missing movie Keywords

In [7]:
# Load the details and existing movie keywords data
details_df = pd.read_csv('../data/Combined_Movies_Details.csv')
keywords_df = pd.read_csv('movie_keywords.csv')

# Extract movie IDs
movie_ids_in_details = details_df['movie_ID'].values
movie_ids_in_keywords = keywords_df['movie_ID'].values

# Find the missing movie IDs (in details but not in keywords)
missing_movie_ids = [movie_id for movie_id in movie_ids_in_details if movie_id not in movie_ids_in_keywords]

# List to store the new movie keyword details
new_movie_keywords = []

# Loop through the missing movie IDs and fetch keywords from TMDB API
for movie_id in missing_movie_ids:
    try:
        # Fetch movie keywords data from the TMDB API
        response = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}/keywords?api_key={api_key}')
        movie_data = response.json()

        # Extract the keywords from the response
        keywords = [keyword['name'] for keyword in movie_data.get('keywords', [])]

        # Create a dictionary with movie ID and its keywords
        movie_keywords = {
            'movie_ID': movie_id,
            'keywords': ', '.join(keywords)  # Join the keywords as a string
        }

        # Add the movie keyword details to the list
        new_movie_keywords.append(movie_keywords)

    except Exception as e:
        print(f"Error fetching details for movie ID {movie_id}: {e}")

# Convert the new movie keywords details to a DataFrame
new_keywords_df = pd.DataFrame(new_movie_keywords)

# Append the new movie keywords to the existing movie_keywords.csv
new_keywords_df.to_csv('movie_keywords.csv', mode='a', header=False, index=False)

print(f"Successfully fetched and appended keywords for {len(new_movie_keywords)} movies.")

Successfully fetched and appended keywords for 10 movies.

### Merging the keywords back to the complete dataset

In [10]:
# Read the complete_movie_dataset and movie_keywords.csv
complete_movie_dataset = pd.read_csv('../data/complete_movie_dataset.csv')
movie_keywords = pd.read_csv('movie_keywords.csv')

# Merge the datasets based on the 'movie_ID' column
updated_movie_dataset = complete_movie_dataset.merge(movie_keywords, on='movie_ID', how='left')

# Save the updated dataset back to complete_movies_dataset.csv
updated_movie_dataset.to_csv('../data/complete_movie_dataset.csv', index=False)

print("Datasets successfully merged and saved back to complete_movie_dataset.csv")

Datasets successfully merged and saved back to complete_movie_dataset.csv